spring:
  profiles:
    active: local
  application:
    name: rt_chat_translation
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  #        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
google:
  cloud:
    credentials:
      location: classpath:rtchatwithtranslation-8f3847ebc62c.json
