GET http://localhost:8080/chat-room/85c0c80e-7125-478a-ae36-d9bd1405ee53
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5NjUyODgzMyIsInVzZXJuYW1lIjoiY2FpbiIsImlhdCI6MTcxNzQxODMwMywiZXhwIjoxNzE3NDU0MzAzfQ.nnJ57-fOjGlVheAeJtRHSYG4tg741zCnm61DluAF-mQ

